names = '''Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo in vitae turpis massa sed elementum tempus egestas. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Eu turpis egestas pretium aenean pharetra magna ac placerat. Mi proin sed libero enim sed faucibus turpis in eu. Nunc congue nisi vitae suscipit tellus mauris. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Auctor elit sed vulputate mi. Neque ornare aenean euismod elementum nisi quis eleifend. Habitant morbi tristique senectus et netus et. Lobortis scelerisque fermentum dui faucibus. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor. Amet mattis vulputate enim nulla aliquet porttitor lacus. Lorem ipsum dolor sit amet consectetur. Viverra aliquet eget sit amet tellus cras adipiscing. Rhoncus dolor purus non enim praesent elementum facilisis leo. Posuere urna nec tincidunt praesent semper feugiat nibh sed.
Vitae elementum curabitur vitae nunc sed velit dignissim sodales ut. Vitae tortor condimentum lacinia quis vel eros donec ac. Malesuada nunc vel risus commodo viverra. Nunc id cursus metus aliquam. Aliquam sem fringilla ut morbi tincidunt augue. Neque convallis a cras semper auctor neque. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Suscipit adipiscing bibendum est ultricies integer quis. Eu consequat ac felis donec et. Interdum velit euismod in pellentesque massa placerat duis. Neque convallis a cras semper auctor neque vitae tempus quam. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Ut faucibus pulvinar elementum integer enim neque volutpat ac. Amet mauris commodo quis imperdiet massa tincidunt nunc.
Non pulvinar neque laoreet suspendisse interdum consectetur libero id. Diam phasellus vestibulum lorem sed risus. Neque egestas congue quisque egestas diam in. Ullamcorper eget nulla facilisi etiam dignissim. Adipiscing diam donec adipiscing tristique risus nec. Aliquam purus sit amet luctus venenatis lectus magna fringilla. Metus dictum at tempor commodo ullamcorper. Morbi tristique senectus et netus. Sem integer vitae justo eget magna fermentum. Quam quisque id diam vel. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Leo urna molestie at elementum eu facilisis sed. Ac turpis egestas sed tempus. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Congue nisi vitae suscipit tellus mauris. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt id. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam.
Congue eu consequat ac felis donec et. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Quisque non tellus orci ac auctor augue mauris augue neque. Justo eget magna fermentum iaculis eu non diam phasellus vestibulum. Lacus sed viverra tellus in hac habitasse. Viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Placerat in egestas erat imperdiet sed euismod nisi porta lorem. Nibh praesent tristique magna sit amet purus gravida. Commodo elit at imperdiet dui accumsan. Aliquet nibh praesent tristique magna sit. Rhoncus dolor purus non enim praesent elementum. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. Turpis cursus in hac habitasse platea dictumst quisque. Vehicula ipsum a arcu cursus.
Faucibus et molestie ac feugiat. Viverra maecenas accumsan lacus vel facilisis volutpat est velit egestas. Diam maecenas sed enim ut sem viverra aliquet eget. Velit euismod in pellentesque massa placerat duis ultricies lacus. Amet dictum sit amet justo donec enim. Semper risus in hendrerit gravida. Sit amet tellus cras adipiscing enim eu. Praesent tristique magna sit amet purus gravida quis. Turpis tincidunt id aliquet risus feugiat. Sit amet porttitor eget dolor morbi non. Morbi non arcu risus quis varius quam quisque id diam. Eu facilisis sed odio morbi quis.
Non pulvinar neque laoreet suspendisse. Convallis posuere morbi leo urna molestie. Quis auctor elit sed vulputate mi. Urna porttitor rhoncus dolor purus non enim praesent. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Sit amet aliquam id diam. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Eget nunc lobortis mattis aliquam faucibus purus in. Donec ultrices tincidunt arcu non sodales neque sodales ut. Facilisi cras fermentum odio eu feugiat. At in tellus integer feugiat. Diam quam nulla porttitor massa id neque aliquam vestibulum morbi. Tortor at risus viverra adipiscing at in tellus integer. Ipsum faucibus vitae aliquet nec. Augue lacus viverra vitae congue eu consequat. Eget egestas purus viverra accumsan in. Nec sagittis aliquam malesuada bibendum. Ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Habitant morbi tristique senectus et.
Sem et tortor consequat id. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Faucibus scelerisque eleifend donec pretium vulputate sapien. Eget arcu dictum varius duis at consectetur lorem donec. Sit amet consectetur adipiscing elit. Varius sit amet mattis vulputate enim. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Phasellus faucibus scelerisque eleifend donec. Neque egestas congue quisque egestas diam in arcu cursus.
Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Dui accumsan sit amet nulla facilisi morbi. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Lacus laoreet non curabitur gravida arcu ac tortor dignissim. Pulvinar elementum integer enim neque volutpat ac. Ut sem nulla pharetra diam sit amet nisl. Sapien pellentesque habitant morbi tristique senectus et netus et malesuada. Aliquam sem et tortor consequat id porta nibh venenatis cras. Vitae proin sagittis nisl rhoncus. Pellentesque habitant morbi tristique senectus et. Sed faucibus turpis in eu mi bibendum neque egestas congue. Mi quis hendrerit dolor magna eget. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Sit amet consectetur adipiscing elit ut. Nibh tortor id aliquet lectus.
Risus quis varius quam quisque id diam vel. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Nunc id cursus metus aliquam eleifend mi in nulla. Id ornare arcu odio ut sem nulla pharetra diam. Consectetur adipiscing elit pellentesque habitant. Etiam sit amet nisl purus in mollis nunc sed. Sed lectus vestibulum mattis ullamcorper. Aliquet porttitor lacus luctus accumsan tortor posuere. Laoreet sit amet cursus sit amet. Netus et malesuada fames ac turpis egestas integer. Neque volutpat ac tincidunt vitae semper quis lectus nulla at.
Nulla facilisi nullam vehicula ipsum. Eget velit aliquet sagittis id consectetur purus. Libero justo laoreet sit amet cursus sit amet dictum sit. Eget duis at tellus at urna condimentum mattis pellentesque id. Semper auctor neque vitae tempus quam pellentesque nec nam. Et odio pellentesque diam volutpat commodo sed. Quis lectus nulla at volutpat. Fermentum et sollicitudin ac orci phasellus egestas tellus. Dolor sed viverra ipsum nunc. Facilisi nullam vehicula ipsum a arcu cursus vitae. Nunc congue nisi vitae suscipit tellus.
Tincidunt dui ut ornare lectus sit amet. Gravida in fermentum et sollicitudin ac orci phasellus egestas. Adipiscing elit ut aliquam purus sit amet. Blandit turpis cursus in hac habitasse platea dictumst. Vitae ultricies leo integer malesuada. Elit sed vulputate mi sit. Iaculis nunc sed augue lacus viverra vitae congue eu. Mauris sit amet massa vitae tortor. Cras semper auctor neque vitae tempus. Gravida in fermentum et sollicitudin ac orci phasellus egestas tellus. Lacinia quis vel eros donec. Sagittis purus sit amet volutpat consequat mauris.
Mi proin sed libero enim sed faucibus turpis in. Sed id semper risus in hendrerit gravida. Massa sapien faucibus et molestie ac feugiat sed lectus. Nam libero justo laoreet sit amet. Eget nullam non nisi est sit. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Aliquet lectus proin nibh nisl condimentum id venenatis a. Integer feugiat scelerisque varius morbi enim nunc. Tristique nulla aliquet enim tortor at. Laoreet id donec ultrices tincidunt arcu non. Ultricies tristique nulla aliquet enim tortor at. Vitae semper quis lectus nulla at. A condimentum vitae sapien pellentesque habitant morbi. Pharetra magna ac placerat vestibulum lectus. Ut tortor pretium viverra suspendisse potenti nullam ac.
Mauris in aliquam sem fringilla ut morbi tincidunt augue. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Molestie a iaculis at erat pellentesque adipiscing. Tortor posuere ac ut consequat semper viverra nam libero. Aenean vel elit scelerisque mauris pellentesque. Interdum varius sit amet mattis. Massa sed elementum tempus egestas sed sed risus. Tristique risus nec feugiat in. Ultrices sagittis orci a scelerisque purus semper eget duis at. Tellus cras adipiscing enim eu turpis egestas pretium.
Id aliquet lectus proin nibh. Ut morbi tincidunt augue interdum. Cursus metus aliquam eleifend mi in nulla. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Sit amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Cras fermentum odio eu feugiat pretium nibh ipsum consequat. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Et tortor at risus viverra adipiscing at. Et ligula ullamcorper malesuada proin libero nunc consequat. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Mattis ullamcorper velit sed ullamcorper morbi tincidunt. Erat velit scelerisque in dictum non consectetur a erat. Ultricies lacus sed turpis tincidunt id. Consectetur a erat nam at lectus urna duis convallis. Faucibus et molestie ac feugiat sed. Eget nunc lobortis mattis aliquam faucibus purus in massa tempor. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Nunc congue nisi vitae suscipit tellus mauris a diam.
Dui sapien eget mi proin sed libero enim sed. In ornare quam viverra orci sagittis. Nec dui nunc mattis enim. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut consequat. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Quis vel eros donec ac odio tempor orci dapibus ultrices. Nisi est sit amet facilisis magna. Varius sit amet mattis vulputate enim nulla aliquet porttitor. Lorem ipsum dolor sit amet consectetur. Consequat id porta nibh venenatis cras sed felis eget velit. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse.
Convallis a cras semper auctor. Ut placerat orci nulla pellentesque dignissim enim sit. Feugiat in ante metus dictum at tempor commodo ullamcorper. Molestie ac feugiat sed lectus vestibulum. Viverra suspendisse potenti nullam ac. Scelerisque in dictum non consectetur. Aliquet bibendum enim facilisis gravida neque convallis a cras. Eget lorem dolor sed viverra ipsum nunc. Nunc lobortis mattis aliquam faucibus purus in massa tempor. Consequat id porta nibh venenatis cras sed felis. Est placerat in egestas erat imperdiet sed euismod nisi porta. Pretium nibh ipsum consequat nisl vel pretium. Aliquet enim tortor at auctor urna. Est ullamcorper eget nulla facilisi etiam dignissim. Risus quis varius quam quisque id diam vel quam elementum. Nibh venenatis cras sed felis eget velit aliquet sagittis id. Proin sed libero enim sed faucibus turpis in eu mi. Augue eget arcu dictum varius duis at consectetur.
Lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Velit scelerisque in dictum non consectetur. Turpis in eu mi bibendum neque egestas congue. Arcu odio ut sem nulla pharetra diam sit. Dictum at tempor commodo ullamcorper a lacus vestibulum sed. Lacus laoreet non curabitur gravida. Convallis posuere morbi leo urna molestie at. Volutpat lacus laoreet non curabitur gravida arcu. Suscipit tellus mauris a diam. Sem fringilla ut morbi tincidunt augue interdum velit. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Augue eget arcu dictum varius duis at.
Lacus sed turpis tincidunt id aliquet risus. In dictum non consectetur a. Tortor consequat id porta nibh venenatis cras. Orci phasellus egestas tellus rutrum tellus pellentesque. Mattis rhoncus urna neque viverra justo nec ultrices dui. Sed odio morbi quis commodo. Odio eu feugiat pretium nibh. Nam at lectus urna duis convallis. Mattis enim ut tellus elementum sagittis vitae et leo. Ultricies integer quis auctor elit sed vulputate. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Ut faucibus pulvinar elementum integer.
Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Condimentum lacinia quis vel eros. Et netus et malesuada fames ac turpis. Ac auctor augue mauris augue neque gravida in fermentum et. Morbi tristique senectus et netus et malesuada. Cursus turpis massa tincidunt dui ut. Nulla pharetra diam sit amet. Faucibus turpis in eu mi bibendum neque egestas congue quisque. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Facilisi morbi tempus iaculis urna id volutpat lacus.'''

# column 지정
col = 20
words_list = names.split()
tmp_list = []
for i in range(col):
    test_1 = []
    test_2 = []
    for j, n in enumerate(words_list):
        if j % col == i:
            test_1.append(n + "_" + str(j))
            test_2.append(n)
    max_col_len = len(max(test_2, key=len))
    tmp_list.extend([k + "_" + str(max_col_len) for k in test_1])


def sort_func(w):
    return int(w.split("_")[1])


tmp_list.sort(key=sort_func)
print(tmp_list)
result_list = [n.split("_")[0].ljust(int(n.split("_")[2]) + 1) for n in tmp_list]

result = ''
for i, s in enumerate(result_list):
    if i % col == 0:
        s = '\n' + s
    result += s
# 출력
print(result)
